steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-backend:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'backend/Dockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Backend'
    args:
      - 'run'
      - 'deploy'
      - 'ai-hiring-tool-backend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-backend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--port=8000'
      - '--allow-unauthenticated'
      - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest,ASSEMBLYAI_API_KEY=assemblyai-api-key:latest,GOOGLE_APPLICATION_B64=google-application-b64:latest'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend Image'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-frontend:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend Image'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy Frontend'
    args:
      - 'run'
      - 'deploy'
      - 'ai-hiring-tool-frontend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-frontend:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--port=8080'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-backend:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ai-hiring-repo/ai-hiring-tool-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY