services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai_hiring_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_hiring_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules